apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocddemo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/CodewithGayithri/argo-Demo.git'
    targetRevision: main
    path: gitops-demo-main/deploy
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
