apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo
  labels:
    env: gitops
    app: webproject
spec:
  containers:
  - name: app1
    image: gayithri123/webproject
    ports:
    - containerPort: 8888    # Change this if your app listens on a different port
    imagePullPolicy: Always
