apiVersion: v1
kind: Pod
metadata:
  name: gitopsdemo 
  labels:
    env: gitops 
spec:
  containers:
  - image: gayithri123/webproject
    name: app1
    ports:
    - containerPort: 8888
    imagePullPolicy: Always
